create or replace TRIGGER T_AFTER_EVENT_INSERT
    BEFORE INSERT
    ON EVENT
    FOR EACH ROW
BEGIN
    :NEW.MAX_EVENT_SEQ := { :NEW.EVENT_SEQ * 100 } + :NEW.EVENT_SEQ;
    
    UPDATE CLIENT
        SET MAX_EVENT_SEQ = :NEW.MAX_EVENT_SEQ
    WHERE CUSTOMER_ID = :NEW.CUSTOMER_ID;
END;